version: "3.8"
services:
  app:
    build: .
    container_name: TLExemploReact-dev
    ports:
      - "3016:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - NODE_ENV=development
    networks:
      - tlserver-dev
    restart: unless-stopped
networks:
  tlserver-dev:
    driver: bridge