name: Deploy DEV
on:
  push:
    branches: [develop]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Deploy to DEV
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          key: ${{ secrets.DEPLOY_PRIVATE_KEY }}
          script: |
            cd ~/docker/projetos/TLExemploReact
            git pull origin develop
            docker compose -p tlexemploreact-dev -f docker-compose.dev.yml build --no-cache
            docker compose -p tlexemploreact-dev -f docker-compose.dev.yml up -d